name: Scheduled Deploy

on:
  schedule:
    - cron: '0 */12 * * *'  # Set the cron schedule to run every 12 hours

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to Vercel
      run: |
        curl -X POST -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
        https://api.vercel.com/v1/now/deployments --data '{"name": "astro-portfolio"}'
